### ISSUE TITLE
Check out adding Emotes to the TextField

### ISSUE THREAD

**Issue by thePlebDev** [thePlebDev/Clicker#1406]
# Proposed change
- I want the user to be able to click on emotes and have them appear in the TextField
- first I want to check with the simple `LUL` emote

# Why is this important
- This will give users the ability to see the actual emotes and not just the name of the UI()

# Additional context
- [HERE](https://developer.android.com/reference/kotlin/androidx/compose/foundation/text/package-summary#BasicText(androidx.compose.ui.text.AnnotatedString,androidx.compose.ui.Modifier,androidx.compose.ui.text.TextStyle,kotlin.Function1,androidx.compose.ui.text.style.TextOverflow,kotlin.Boolean,kotlin.Int,kotlin.Int,kotlin.collections.Map,androidx.compose.ui.graphics.ColorProducer)) is a link to the documentation of the TextField with an AnnotatedString

**Comment by thePlebDev** [comment]
- THis can 100000000% be done!!!!!!!!!!!!!!!!!!! Here is the code to prove it:
```kotlin
@Composable
fun SimpleFilledTextFieldSample(  
    inlineContentMap: EmoteListMap,
) {
    
    val text = buildAnnotatedString {
        
        appendInlineContent("LUL", "Lul not found")
    }
    BasicText(
        text = text,
        inlineContent = inlineContentMap.map,
        modifier = Modifier.fillMaxWidth()
    )

  
}

```
- However, I will be putting this feature on the back burning and will only implement it after I have all the other emote functions worked out

**Comment by thePlebDev** [comment]
- turns out this is a little harder than expected. [HERE](https://stackoverflow.com/questions/78145214/android-compose-textfield-with-image-using-inlinetextcontent) is a link to a stackoverflow with a similar problem

**Comment by thePlebDev** [comment]
- [HERE ](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/BasicTextField.kt?q=BasicTextField&ss=androidx%2Fplatform%2Fframeworks%2Fsupport) is the source code for the starting of the TextField
- I am looking into it because I need to find out how the text field moves when the maxline amount is hit

**Comment by thePlebDev** [comment]
[This is the BasicTextField that is being used for out TextField](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/BasicTextField.kt;l=593?q=BasicTextField&ss=androidx%2Fplatform%2Fframeworks%2Fsupport)

**Comment by thePlebDev** [comment]
- Whos values then get passed to [CoreTextField](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/CoreTextField.kt)

**Comment by thePlebDev** [comment]
[This could be the layout modifier I was looking for](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/text/TextFieldScroll.kt;l=110)

**Comment by RetRo99** [comment]
Did you manage to resolve this? It does not look to be currently possible with compose

**Comment by thePlebDev** [comment]
@RetRo99 it most certainly possible. However, it is not native. Meaning that we have to get creative with the implementation. I have not found a perfect solution. This solution is buggy but what I ended up doing was using a textField, making it hidden and then laying a normal `Text` overtop of it and using a `InlineTextContent`  to show the emotes to the user. However, there was a layout bug when the user typed more than 10 lines. 
- What I would recommend is to message android engineers that work at `Slack` (slack has this implemented in their app) and ask them for help

**Comment by thePlebDev** [comment]
- [HERE](https://dev.to/theplebdev/adding-icons-to-text-in-jetpack-compose-with-kotlin-and-android-37el) is my blog post on `InlineTextContent`. The blog post its self is a little confusing but it does have all of the resources I used

**Comment by thePlebDev** [comment]
Also, if you do end up messaging the Slack engineers. Please let me know what they say
